name: souglink
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17
  flutter_localizations:
    sdk: flutter
  fl_chart: 0.69.2
  sqflite: ^2.0.0+3
  flutter_bloc: ^8.0.0
  bloc: ^8.0.0
  equatable: ^2.0.5
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_database: ^11.1.4
  cloud_firestore: ^5.6.3
  image_picker: ^1.1.2
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  firebase_storage: ^12.4.2
  firebase_messaging: ^15.2.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/.
    - assets/backgroundlogin.jpg
    - assets/logo.png
    - assets/profile.jpg
    - assets/potato.jpg
    - assets/farmer.png
    - assets/truck.png
    - assets/tomato.png
    - assets/seller1.jpg
    - assets/seller2.jpg
    - assets/seller3.webp

  fonts:
    - family: NotoSansArabic_SemiCondensed
      fonts:
        - asset: assets/fonts/NotoSansArabic_SemiCondensed-Bold.ttf
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-ExtraBold.ttf
